server:
  port: 8540

spring:
  application:
    name: wind
  datasource:
    url: jdbc:h2:localhost/~/wind_dev
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
